"""
app/models/notification.py
----------------------------
In-app notification model. Notifications are generated by
services/notification_service.py for events such as approaching deadlines,
delayed equipment, or progress updates, and shown in the navbar bell icon.
"""

from datetime import datetime
from app.extensions import db


class NotificationType:
    INFO = "info"
    WARNING = "warning"
    DANGER = "danger"
    SUCCESS = "success"


class Notification(db.Model):
    __tablename__ = "notifications"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    title = db.Column(db.String(200), nullable=False)
    message = db.Column(db.Text)
    notification_type = db.Column(db.String(20), default=NotificationType.INFO)
    link = db.Column(db.String(255))  # optional internal URL to navigate to
    is_read = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<Notification {self.title} user={self.user_id}>"
